#!/usr/bin/env bash
CUSTOM_BASH_LOCATION="$HOME/dotfiles/custom_bash"
alias tmuxatk="tmux attach -t"
alias vim="nvim"
alias v="nvim"
alias .file="cd ~/dotfiles"
alias ls="lsd"
alias l="lsd -Fl"
alias ide="$CUSTOM_BASH_LOCATION/tmux-ide.sh"
alias tree="lsd --tree -X"
alias html="~/dotfiles/custom_bash/new_html/newhtml.sh"
alias live-server="live-server --browser=chromium"
alias cexe="$CUSTOM_BASH_LOCATION/cexe.sh"
alias cppexe="$CUSTOM_BASH_LOCATION/cppexe.sh"
alias mvmk="$CUSTOM_BASH_LOCATION/my_mv.sh"
alias mobicam="$CUSTOM_BASH_LOCATION/scrcpy_camera.sh"
alias javaproj="$CUSTOM_BASH_LOCATION/java_proj/java-proj.sh"
alias javex="$CUSTOM_BASH_LOCATION/javex/javex.sh"
alias set_blight="$CUSTOM_BASH_LOCATION/kokoss_backlight.sh"
alias arcaea="$CUSTOM_BASH_LOCATION/arcaea.sh"
alias tmux-profile="$CUSTOM_BASH_LOCATION/tmux-profile.sh"
alias .learn="cd ~/learn"
alias get_screenshot="$CUSTOM_BASH_LOCATION/screenshot.sh"
alias bakdate="date --rfc-3339=seconds | sed 's/\ /_/g'"
alias git-cz="git add . && git-cz && git push"
alias yai="yai -c"
alias work=""
