#!~/.bashrc
CUSTOM_BASH_LOCATION=~/dotfiles/custom_bash

alias tmuxatk="tmux attach -t"
alias vim="nvim"
alias v="nvim"
alias .file="cd ~/dotfiles"
# alias lazygit="$CUSTOM_BASH_LOCATION/lazygit.sh"
alias ls="lsd"
alias l="lsd -Fl"
alias ide="$CUSTOM_BASH_LOCATION/tmux-ide.sh"
alias tree="lsd --tree -X"
# alias lazyweb="$CUSTOM_BASH_LOCATION/lazyweb.sh"
# alias html="~/dotfiles/custom_bash/html.sh"
alias html="~/dotfiles/custom_bash/new_html/newhtml.sh"
alias live-server="live-server --browser=chromium"
alias cexe="$CUSTOM_BASH_LOCATION/cexe.sh"
alias cppexe="$CUSTOM_BASH_LOCATION/cppexe.sh"
alias mvmk="$CUSTOM_BASH_LOCATION/my_mv.sh"
alias mobicam="$CUSTOM_BASH_LOCATION/scrcpy_camera.sh"
alias javaproj="$CUSTOM_BASH_LOCATION/java_proj/java-proj.sh"
alias javex="$CUSTOM_BASH_LOCATION/javex/javex.sh"
alias set_blight="$CUSTOM_BASH_LOCATION/kokoss_backlight.sh"
alias arcaea="$CUSTOM_BASH_LOCATION/arcaea.sh"
[[ -r ~/.config/tmux/tmux.conf ]] || alias tmux="$CUSTOM_BASH_LOCATION/tmux-profile.sh"
alias tmux-profile="$CUSTOM_BASH_LOCATION/tmux-profile.sh"
alias .learn="cd ~/learn"
alias get_screenshot="$CUSTOM_BASH_LOCATION/screenshot.sh"
alias bakdate="date --rfc-3339=seconds | sed 's/\ /_/g'"
alias yai="yai -c"
