#!/usr/bin/env bash
CUSTOM_BASH_LOCATION="$HOME"/dotfiles/scripts
alias tmuxatk="tmux attach -t"
alias vim="nvim"
alias v="nvim"
alias .file="cd ~/dotfiles"
alias ls="lsd"
alias l="lsd -Fl"
alias tree="lsd --tree -X"
alias .learn="cd ~/learn"
alias lazygit="git add . && git-cz && git push"
alias yai="yai -c"
# alias bakdate="date --rfc-3339=seconds | sed 's/\ .*//g'"
alias html="$CUSTOM_BASH_LOCATION/new-html/newhtml.sh"
alias ide="$CUSTOM_BASH_LOCATION/tmux-ide.sh"
alias cexe="$CUSTOM_BASH_LOCATION/cexe.sh"
alias cppexe="$CUSTOM_BASH_LOCATION/cppexe.sh"
alias mvmk="$CUSTOM_BASH_LOCATION/my-mv.sh"
alias mobicam="$CUSTOM_BASH_LOCATION/scrcpy-camera.sh"
alias javaproj="$CUSTOM_BASH_LOCATION/java-proj/java-proj.sh"
alias javex="$CUSTOM_BASH_LOCATION/javex/javex.sh"
# alias setblight="$CUSTOM_BASH_LOCATION/kokoss-backlight.sh"
alias arcaea="$CUSTOM_BASH_LOCATION/arcaea.sh"
alias tmux-profile="$CUSTOM_BASH_LOCATION/tmux-profile.sh"
# alias get_screenshot="$CUSTOM_BASH_LOCATION/screenshot.sh"
alias work="$CUSTOM_BASH_LOCATION/tmux-workspace.sh"
alias multi-rename="$CUSTOM_BASH_LOCATION/multiple-rename.sh"
alias rofitor="~/dotfiles/rofi/applets/bin/monitor.sh 1 1"
